version: '3'
services:
  fastapi-app:
    image: fastapi-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
  
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: botfarm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"