version: '3'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    image: fastapi-app
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      postgres-test-db:
        condition: service_healthy
  
  postgres-db:
    image: postgres:14.11
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test-db:
    image: postgres:14.11
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5